# Generated by Django 5.0.4 on 2025-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationclass',
            name='ends_at',
            field=models.DateTimeField(null=True),
        ),
    ]
