# Generated by Django 5.0.4 on 2025-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_locationclass_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationclass',
            name='ends_at',
            field=models.TimeField(null=True),
        ),
    ]
