# Generated by Django 5.0.4 on 2025-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_locationclass_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationclass',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='locationclass',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
