# Generated by Django 5.0.4 on 2025-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_locationclass_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationclass',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
