# Generated by Django 5.0.4 on 2025-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_locationclass_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=200, null=True)),
                ('student', models.CharField(max_length=200, null=True)),
                ('lecturer_name', models.CharField(max_length=200, null=True)),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('class_name', models.CharField(max_length=100)),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
