# Generated by Django 5.0.4 on 2025-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_registeredclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
