# Generated by Django 5.0.4 on 2025-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_registeredclass_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationclass',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='registered_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
