# Generated by Django 5.0.4 on 2025-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_locationclass_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=200, null=True)),
                ('student', models.CharField(max_length=200, null=True)),
                ('class_name', models.CharField(max_length=100)),
                ('class_minutes', models.DecimalField(decimal_places=1, max_digits=5)),
                ('status', models.CharField(default='No', max_length=100)),
            ],
        ),
    ]
