# Generated by Django 5.0.4 on 2025-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_myclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationclass',
            name='status',
            field=models.CharField(default='OFF', max_length=100),
        ),
    ]
